name: 同步 main 分支到 submit 分支

on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: 同步分支
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 配置 Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
      
      - name: 同步 main 到 submit
        run: |
          git checkout submit
          # 尝试合并，如果有冲突则处理
          if ! git merge main --no-edit; then
            # 如果README.md有冲突，保留submit分支的版本
            if git status | grep -q "README.md"; then
              git checkout --theirs README.md
              git add README.md
            fi
            # 提交解决的冲突
            git commit -m "保留submit分支的README.md"
          fi
          git push origin submit 